name: CI
on:
    push:
    merge_group:
    pull_request:
jobs:
    fmt-check:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: software-mansion/setup-scarb@v1
              with:
                  scarb-version: "0.6.2"
            - run: for dir in ./examples/* ; do cd $dir && scarb fmt --check && cd ../..; done;
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - run: curl -L https://install.dojoengine.org | bash && source ~/.bashrc && dojoup

